/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OfTypewriter {
        "message": string;
        "speed": any;
    }
}
declare global {
    interface HTMLOfTypewriterElement extends Components.OfTypewriter, HTMLStencilElement {
    }
    var HTMLOfTypewriterElement: {
        prototype: HTMLOfTypewriterElement;
        new (): HTMLOfTypewriterElement;
    };
    interface HTMLElementTagNameMap {
        "of-typewriter": HTMLOfTypewriterElement;
    }
}
declare namespace LocalJSX {
    interface OfTypewriter {
        "message"?: string;
        "speed"?: any;
    }
    interface IntrinsicElements {
        "of-typewriter": OfTypewriter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "of-typewriter": LocalJSX.OfTypewriter & JSXBase.HTMLAttributes<HTMLOfTypewriterElement>;
        }
    }
}
